/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmModal: typeof import('./components/modal/ConfirmModal.vue')['default']
    ContainerCard: typeof import('./components/container/ContainerCard.vue')['default']
    ContainerHistoryModal: typeof import('./components/modal/ContainerHistoryModal.vue')['default']
    ContainerInput: typeof import('./components/input/ContainerInput.vue')['default']
    ContainerListItem: typeof import('./components/container/ContainerListItem.vue')['default']
    ContainerTable: typeof import('./components/table/ContainerTable.vue')['default']
    ContainerTableModal: typeof import('./components/modal/ContainerTableModal.vue')['default']
    ContainerTransferList: typeof import('./components/transfer/ContainerTransferList.vue')['default']
    ContainerTransferTable: typeof import('./components/table/ContainerTransferTable.vue')['default']
    ContainerTypeChip: typeof import('./components/container/ContainerTypeChip.vue')['default']
    ContainerTypeSelect: typeof import('./components/input/ContainerTypeSelect.vue')['default']
    CustomAvatar: typeof import('./components/util/CustomAvatar.vue')['default']
    GenericAddEditFormModal: typeof import('./components/modal/GenericAddEditFormModal.vue')['default']
    LoginSection: typeof import('./components/auth/LoginSection.vue')['default']
    ProjectSelect: typeof import('./components/input/ProjectSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrialSelect: typeof import('./components/input/TrialSelect.vue')['default']
    UserCard: typeof import('./components/util/UserCard.vue')['default']
    UserTable: typeof import('./components/table/UserTable.vue')['default']
  }
}
